// <auto-generated />
namespace InventarioOtro.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addDeudas : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addDeudas));
        
        string IMigrationMetadata.Id
        {
            get { return "201902100009142_addDeudas"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
